version: 2.1
jobs:
  build:
    docker:
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building DEAGLE Kernel
          command: |
            wget https://raw.githubusercontent.com/AKPR2007/kernel-sdm660/deagle/build-start.sh
            bash build-start.sh stable clang
            cd kernel
            wget https://raw.githubusercontent.com/AKPR2007/kernel-sdm660/deagle/build.sh
            bash build.sh tulip newcam clang noroot
            bash build.sh tulip oldcam clang noroot
            git apply oc.patch
            bash build.sh tulip newcam oc clang noroot
            bash build.sh tulip oldcam oc clang noroot
            git apply -R oc.patch
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
            bash build.sh tulip newcam clang ksun
            bash build.sh tulip oldcam clang ksun
            git apply oc.patch
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
            bash build.sh tulip newcam oc clang ksun
            bash build.sh tulip oldcam oc clang ksun
            wget https://raw.githubusercontent.com/AKPR2007/kernel-sdm660/deagle/build-final.sh
            bash build-final.sh clang
      - store_artifacts:
          path: /root/project/kernel/kernel-done
